version: '3.8'

services:
  bot:
    build:
      context: ./services/backend-bot
      dockerfile: Dockerfile
    container_name: admarket-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: admarket-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/frontend/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/tgadmarketplace.ru-0001:/etc/letsencrypt/live/tgadmarketplace.ru-0001:ro
    depends_on:
      - bot

  db:
    image: postgres:15
    container_name: admarket-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

