version: '3.8'

services:
  bot:
    build:
      context: ./services/backend-bot
      dockerfile: Dockerfile
    container_name: admarket-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: admarket-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/frontend/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/tgadmarketplace.ru-0001:/etc/letsencrypt/live/tgadmarketplace.ru-0001:ro
    depends_on:
      - bot

