version: '3.8'

services:
  bot:
    build:
      context: ./services/backend-bot
      dockerfile: Dockerfile
    env_file:
      - ./services/backend-bot/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "python3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./services/frontend/certificates:/app/certificates
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 