version: '3.8'

services:
  bot:
    build:
      context: ./services/backend-bot
      dockerfile: Dockerfile
    env_file:
      - ./services/backend-bot/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  admarket-network:
    driver: bridge
  app-network:
    driver: bridge

volumes:
  postgres_data: 