version: '3.8'

services:
  bot:
    build:
      context: ./services/backend-bot
      dockerfile: Dockerfile
    container_name: admarket-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: admarket-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/frontend/nginx/conf.d:/etc/nginx/conf.d
      - ./services/frontend/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - bot

  db:
    image: postgres:15
    container_name: admarket-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 