name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-asyncio pytest-mock
          if [ -f services/backend-bot/requirements.txt ]; then pip install -r services/backend-bot/requirements.txt; fi
          
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Test with pytest
        run: |
          cd services/backend-bot
          python -m pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          context: ./services/backend-bot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admarket-bot:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./services/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admarket-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 87.228.82.67 >> ~/.ssh/known_hosts
          
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@87.228.82.67 "echo 'SSH connection successful'"
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 87.228.82.67
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Starting deployment..."
            cd /root/admarket
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            # Pull latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admarket-bot:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admarket-frontend:latest
            
            # Update docker-compose.yml with new image tags
            sed -i "s|image: .*admarket-bot.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/admarket-bot:latest|" docker-compose.yml
            sed -i "s|image: .*admarket-frontend.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/admarket-frontend:latest|" docker-compose.yml
            
            # Stop and remove old containers
            docker compose down
            
            # Start new containers
            docker compose up -d
            
            # Clean up old images
            docker image prune -f
            
            echo "Deployment completed!" 